name: climaapp
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  geolocator: ^5.3.1
  http: ^0.12.1
  flutter_spinkit: ^4.1.2+1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900

    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf
          weight: 900

    - family: RobotoRegular
      fonts:
        - asset: fonts/RobotoRegular.ttf
          weight: 900

    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 900